server:
  port: 8222 # 服务端口
spring:
  application:
    name: service-gatway # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos服务地址
    gateway:
      discovery:
        locator:
          enabled: true # 使用服务发现路由
#配置service-acl服务
#设置路由id
      routes:
      - id: service-acl
        uri: lb://service-acl
        predicates:
        - Path=/*/acl/**

      - id: service-cms
        uri: lb://service-cms
        predicates:
        - Path=/educms/**

      - id: service-edu-backstage
        uri: lb://service-edu-backstage
        predicates:
        - Path=/eduservice/**

      - id: service-edu-frontstage
        uri: lb://service-edu-frontstage
        predicates:
        - Path=/edufront/**

      - id: service-msm
        uri: lb://service-msm
        predicates:
        - Path=/edumsm/**

      - id: service-order
        uri: lb://service-order
        predicates:
        - Path=/eduorder/**

      - id: service-oss
        uri: lb://service-oss
        predicates:
        - Path=/eduoss/**

      - id: service-statistic
        uri: lb://service-statistic
        predicates:
        - Path=/staservice/**

      - id:  service-ucenter
        uri: lb://service-ucenter
        predicates:
        - Path=/educenter/**

      - id:  service-video
        uri: lb://service-video
        predicates:
        - Path=/eduvdo/**
