server:
  port: 8002
spring:
  application:
    name: service-oss
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #nacos 的地址

aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI5tP62pYEdvy89d7gE6Kp
      keysecret: SxikTLrAGWizoSJUDaI1aHOFpS7qHz
      bucketname: xxx-guli-1010
